dailyfeed:
  services:
    member:
      feign:
        url: ${MEMBER_SERVICE_URL:http://localhost:8084}
        timeout:
          connect: 5000
          read: 10000
    timeline:
      feign:
        url: ${TIMELINE_SERVICE_URL:http://localhost:8082}
        timeout:
          connect: 5000
          read: 10000
    content:
      feign:
        url: ${CONTENT_SERVICE_URL:http://localhost:8081}
        timeout:
          connect: 5000
          read: 10000
    search:
      feign:
        url: ${SEARCH_SERVICE_URL:http://localhost:8083}
        timeout:
          connect: 5000
          read: 10000
    image:
      feign:
        url: ${IMAGE_SERVICE_URL:http://localhost:8085}
        timeout:
          connect: 5000
          read: 10000